name: mvn test
on:
  push:
    paths:
      - '**'
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: mvn install tensor 107
        working-directory: .
        run: |
          cd ..
          git clone https://github.com/datahaki/tensor.git
          cd tensor
          git checkout v107
          mvn clean install -DskipTests=true
      - name: mvn test
        working-directory: .
        run: mvn test -B
